---
# use separate dnf tasks 
# because package only installs one item at a time
- name: System packages | basic system utils (rockylinux)
  become: true
  ansible.builtin.dnf:
    name: "{{ basedeps_packages.redhat }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: System packages | basic system utils (ubuntu)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ basedeps_packages.debian }}"
    state: present
  when: ansible_os_family == 'Debian'
