---
# tasks file for roles/basedeps
- name: System | Repositories | Add CRB repository for RHEL
  become: true
  ansible.builtin.command:
    subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
  when: ansible_facts['distribution'] == "RedHat"


#- name: system packages | install epel repo
#  become: true
#  ansible.builtin.dnf:
#    name: epel-release
#    state: present
#  when: ansible_os_family == 'RedHat'

# use separate yum/apt tasks because package only installs one item at a time
- name: system packages | basic system utils (rockylinux)
  become: true
  ansible.builtin.dnf:
    name: "{{ basedeps_packages.redhat }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: system packages | basic system utils (ubuntu)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ basedeps_packages.debian }}"
    state: present
  when: ansible_os_family == 'Debian'
